### ISSUE TITLE
Getting security vulnerability detected in mem < 4.0.0 from github

### ISSUE THREAD

**Issue by VivekFitkariwala** [sezna/nps#209]
Getting security vulnerability detected in mem < 4.0.0 when using nps.

Solution: Upgrading yargs to latest version which don't use os-locale which has dependency on mem

**Comment by VivekFitkariwala** [comment]
I have added a pull request upgrading yargs and fixing test cases accordingly
https://github.com/sezna/nps/pull/210

**Comment by sezna** [comment]
Thank you for this!
