### ISSUE TITLE
README.md contains a broken link

### ISSUE THREAD

**Issue by RA80533** [sezna/nps#222]
https://github.com/sezna/nps/blob/6eb54ac33b43ac9e2ea55a2cbf1ccb32463a9de8/README.md#L537

The URL on line 537 of the project README is broken. While the resource currently exists on the medium.freecodecamp.org domain, the documentation links to the medium.freecodecamp.com domain. freeCodeCamp may have routed the URL to the correct destination in the past but it currently appears not to.

**Comment by sezna** [comment]
Thanks! I'll go ahead and fix this.
